version: "3.1"
services:
  elysia:
    container_name: api
    build: .
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/docker-entrypoint-initdb.d/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
volumes:
  postgres: